### PR TITLE
Make map_from_arrays and map_from_pairs generic

### PR DESCRIPTION
**Pull request by dvic**
This PR makes the `map_from_arrays` and `map_from_pairs` accept values that can be turned into an iterator. This avoids additional allocations required to have a slice when calling these functions.

### CODE REVIEW

**Comment by dvic** [comment]
Should be good now 👍

**Comment by dvic** [comment]
Not sure why the clippy started complaining about the lifetimes in `binary.rs` and `list.rs`, fixed that by removing those lifetimes.

**Comment by evnu** [comment]
Thanks for the PR! Do you maybe have a benchmark how much this saves?

**Comment by dvic** [comment]
> Thanks for the PR! Do you maybe have a benchmark how much this saves?

Thanks for asking because I have no idea why, but this PR is 10x slower 😀, I'll have to investigate...

**Comment by dvic** [comment]
@evnu I figured it out but now the "correct" implementation is a breaking change. It comes down to `&(A, B)` vs `(&A, &B)`. When I make the iterator type `(&A, &B)`, the performance is the same but I can't pass `&a` where `let a: Vec<(A, B)>` anymore, which is a breaking change. For now I'm going to close this PR as there is no increased performance benefit and then it doesn't justify a breaking change I think.

**Pull request closed without merging**
