### PR TITLE
Rename Pid to LocalPid

### PR DESCRIPTION
**Pull request by filmor**

### CODE REVIEW

**Comment by hansihe** [comment]
Does it have a type alias for backwards compatibility?

**Comment by scrogson** [comment]
I don't know how I feel about this one. We definitely need to add a type alias in order to not break existing projects. What is the behaviour when using `Env::send` or `OwnedEnv::send_and_clear` with remote pids? Does it crash?

If we can't prevent a remote pid from being passed into a NIF, I don't think renaming it to `LocalPid` makes much difference here.

**Comment by filmor** [comment]
I'll add the type alias. You can't create an object of (C) type `ErlNifPid` that refers to a remote pid, cf http://erlang.org/doc/man/erl_nif.html#ErlNifPid. You can have a term that points to a remote pid, but you can't do much with it apart from passing it around in NIFs.

**Comment by evnu** [comment]
> If we can't prevent a remote pid from being passed into a NIF, I don't think renaming it to LocalPid makes much difference here.

I think renaming helps as it indicates clearly that the PID type is restrictive. I once tried using a remote pid and was confused until I understood that decoding a remote PID is not possible. This would not have happened if the type was named `LocalPid`.

**Comment by filmor** [comment]
It would be really nice if we merged this before the next release, the sooner we get the deprecation warning in the better.

**Pull request merged**
