### PR TITLE
Add clippy

### LINKED ISSUE #222: Make use of clippy?
I played around with `cargo clippy` and rustler the other day and wondered if there is interest to bring that upstream. I fixed the warnings from `cargo clippy --all-features --all-targets` in a [branch](https://github.com/evnu/rustler/tree/clippy). The suggestions mainly aimed at removing superfluous (as of Rust 2018) lifetime annotations, removing unnecessary captures and replacing references where move is more appropriate due to `Copy` being implemented for a type. But clippy found two things which might be of interest:

1. `bin.as_mut_slice().write(self.as_bytes()).expect("memory copy of string failed")` should use `write_all()` instead of `write`, as `write` does not guarantee to write all at once
2. `ptr.offset(offset as isize)` should be `ptr.add(offset)`, as `offset` can never be a negative number.

### PR DESCRIPTION
**Pull request by evnu**
This pull requests adds [clippy](https://github.com/rust-lang/rust-clippy) to travis. I fixed the current clippy suggestions within Rustler. I left out some suggestions to show what they look like.

To run clippy against Rustler:

```
$ rustup component add clippy
$ cargo clippy --all-targets --all-features -- -D warnings
```

Fix #222.

### CODE REVIEW

**Comment by evnu** [comment]
The remaining errors are in `erlang_nif_sys`. I will fix them if there is interest to merge this pull request.

**Comment by hansihe** [comment]
Definitely interested in merging this.

Would be nice if you could fix the remaining errors and add the change to the changelog

**Comment by evnu** [comment]
> Would be nice if you could fix the remaining errors and add the change to the changelog

Will do.

**Comment by evnu** [comment]
> Will do.

Done.

**Pull request merged**
